{{- if and ( eq .Values.autoScaling.enabled true) ( eq .Values.autoScaling.keda.enabled false) -}}
apiVersion: {{ include "hpa.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.service_name }}
  labels:
    app: {{ .Values.service_name | quote }}
    environment: {{ .Values.environment | quote }}
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: {{ .Values.service_name | quote }}
    app.kubernetes.io/version: {{ .Values.image.tag | quote }}
    app.kubernetes.io/part-of: {{  .Values.project_name | quote }}
    product:  {{  .Values.product | quote }}
    version: {{ .Values.image.tag | quote }}
    owner: {{  .Values.owner | quote }}
  annotations:
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.service_name }}
  minReplicas: {{ .Values.autoScaling.minReplicas }}
  maxReplicas: {{ .Values.autoScaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoScaling.cpuAverageUtilization }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoScaling.memoryAverageUtilization }}
{{- end }}